// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.accounts */
export type AccountsId = number;

/** Represents the table public.accounts */
export default interface Accounts {
  id: AccountsId;

  userId: number;

  type: string;

  provider: string;

  providerAccountId: string;

  refreshToken: string | null;

  accessToken: string | null;

  expiresAt: string | null;

  idToken: string | null;

  scope: string | null;

  sessionState: string | null;

  tokenType: string | null;
}

/** Represents the initializer for the table public.accounts */
export interface AccountsInitializer {
  /** Default value: nextval('accounts_id_seq'::regclass) */
  id?: AccountsId;

  userId: number;

  type: string;

  provider: string;

  providerAccountId: string;

  refreshToken?: string | null;

  accessToken?: string | null;

  expiresAt?: string | null;

  idToken?: string | null;

  scope?: string | null;

  sessionState?: string | null;

  tokenType?: string | null;
}

/** Represents the mutator for the table public.accounts */
export interface AccountsMutator {
  id?: AccountsId;

  userId?: number;

  type?: string;

  provider?: string;

  providerAccountId?: string;

  refreshToken?: string | null;

  accessToken?: string | null;

  expiresAt?: string | null;

  idToken?: string | null;

  scope?: string | null;

  sessionState?: string | null;

  tokenType?: string | null;
}
