// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.campaign */
export type CampaignName = string;

/** Identifier type for public.campaign */
export type CampaignCompany = string;

/** Represents the table public.campaign */
export default interface Campaign {
  name: CampaignName;

  company: CampaignCompany;

  startDate: Date;

  endDate: Date;

  reminderDates: Date[];

  customerEmails: string[] | null;

  measureValues: unknown[];
}

/** Represents the initializer for the table public.campaign */
export interface CampaignInitializer {
  name: CampaignName;

  company: CampaignCompany;

  startDate: Date;

  endDate: Date;

  reminderDates: Date[];

  customerEmails?: string[] | null;

  measureValues: unknown[];
}

/** Represents the mutator for the table public.campaign */
export interface CampaignMutator {
  name?: CampaignName;

  company?: CampaignCompany;

  startDate?: Date;

  endDate?: Date;

  reminderDates?: Date[];

  customerEmails?: string[] | null;

  measureValues?: unknown[];
}
