// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.company */
export type CompanyName = string;

/** Represents the table public.company */
export default interface Company {
  name: CompanyName;

  email: string;
}

/** Represents the initializer for the table public.company */
export interface CompanyInitializer {
  name: CompanyName;

  email: string;
}

/** Represents the mutator for the table public.company */
export interface CompanyMutator {
  name?: CompanyName;

  email?: string;
}
