// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.customer_measurement */
export type Customer_measurementCampaign_name = string;

/** Identifier type for public.customer_measurement */
export type Customer_measurementCustomer_mail = string;

/** Identifier type for public.customer_measurement */
export type Customer_measurementCompany = string;

/** Represents the table public.customer_measurement */
export default interface CustomerMeasurement {
  campaignName: Customer_measurementCampaign_name;

  customerMail: Customer_measurementCustomer_mail;

  company: Customer_measurementCompany;

  measurements: unknown[];

  dateTime: Date;
}

/** Represents the initializer for the table public.customer_measurement */
export interface CustomerMeasurementInitializer {
  campaignName: Customer_measurementCampaign_name;

  customerMail: Customer_measurementCustomer_mail;

  company: Customer_measurementCompany;

  measurements: unknown[];

  dateTime: Date;
}

/** Represents the mutator for the table public.customer_measurement */
export interface CustomerMeasurementMutator {
  campaignName?: Customer_measurementCampaign_name;

  customerMail?: Customer_measurementCustomer_mail;

  company?: Customer_measurementCompany;

  measurements?: unknown[];

  dateTime?: Date;
}
