// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.customer */
export type CustomerEmail = string;

/** Identifier type for public.customer */
export type CustomerCompany = string;

/** Represents the table public.customer */
export default interface Customer {
    email: CustomerEmail;

    company: CustomerCompany;

    id: string;

    title: string | null;

    firstName: string;

    middleName: string | null;

    lastName: string;

    streetLines: string[];

    postalCode: string;

    city: string;

    country: string;

    stateOrProvince: string;

    phoneNumber: string;
}

/** Represents the initializer for the table public.customer */
export interface CustomerInitializer {
    email: CustomerEmail;

    company: CustomerCompany;

    /** Default value: uuidv7_sub_ms() */
    id?: string;

    title?: string | null;

    firstName: string;

    middleName?: string | null;

    lastName: string;

    streetLines: string[];

    postalCode: string;

    city: string;

    country: string;

    stateOrProvince: string;

    phoneNumber: string;
}

/** Represents the mutator for the table public.customer */
export interface CustomerMutator {
    email?: CustomerEmail;

    company?: CustomerCompany;

    id?: string;

    title?: string | null;

    firstName?: string;

    middleName?: string | null;

    lastName?: string;

    streetLines?: string[];

    postalCode?: string;

    city?: string;

    country?: string;

    stateOrProvince?: string;

    phoneNumber?: string;
}
