// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.customer */
export type CustomerId = string;

/** Identifier type for public.customer */
export type CustomerCompany = string;

/** Represents the table public.customer */
export default interface Customer {
  id: CustomerId;

  company: CustomerCompany;

  email: string;

  title: string | null;

  firstName: string;

  middleName: string | null;

  lastName: string;

  phoneNumber: string | null;

  entityId: string;

  additionalFields: unknown | null;
}

/** Represents the initializer for the table public.customer */
export interface CustomerInitializer {
  /** Default value: uuidv7_sub_ms() */
  id?: CustomerId;

  company: CustomerCompany;

  email: string;

  title?: string | null;

  firstName: string;

  middleName?: string | null;

  lastName: string;

  phoneNumber?: string | null;

  entityId: string;

  additionalFields?: unknown | null;
}

/** Represents the mutator for the table public.customer */
export interface CustomerMutator {
  id?: CustomerId;

  company?: CustomerCompany;

  email?: string;

  title?: string | null;

  firstName?: string;

  middleName?: string | null;

  lastName?: string;

  phoneNumber?: string | null;

  entityId?: string;

  additionalFields?: unknown | null;
}
