// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.discount */
export type DiscountDiscount_name = string;

/** Identifier type for public.discount */
export type DiscountCampaign_name = string;

/** Identifier type for public.discount */
export type DiscountCompany = string;

/** Identifier type for public.discount */
export type DiscountDiscount_type = string;

/** Identifier type for public.discount */
export type DiscountMeasure_value = string;

/** Identifier type for public.discount */
export type DiscountRange_from = string;

/** Identifier type for public.discount */
export type DiscountValid_from = Date;

/** Represents the table public.discount */
export default interface Discount {
  discountName: DiscountDiscount_name;

  campaignName: DiscountCampaign_name;

  company: DiscountCompany;

  discountType: DiscountDiscount_type;

  measureValue: DiscountMeasure_value;

  rangeFrom: DiscountRange_from;

  validFrom: DiscountValid_from;

  rangeTo: string | null;

  discountValue: string;

  discountUnit: string;

  validTo: Date;
}

/** Represents the initializer for the table public.discount */
export interface DiscountInitializer {
  discountName: DiscountDiscount_name;

  campaignName: DiscountCampaign_name;

  company: DiscountCompany;

  discountType: DiscountDiscount_type;

  measureValue: DiscountMeasure_value;

  rangeFrom: DiscountRange_from;

  validFrom: DiscountValid_from;

  rangeTo?: string | null;

  discountValue: string;

  discountUnit: string;

  validTo: Date;
}

/** Represents the mutator for the table public.discount */
export interface DiscountMutator {
  discountName?: DiscountDiscount_name;

  campaignName?: DiscountCampaign_name;

  company?: DiscountCompany;

  discountType?: DiscountDiscount_type;

  measureValue?: DiscountMeasure_value;

  rangeFrom?: DiscountRange_from;

  validFrom?: DiscountValid_from;

  rangeTo?: string | null;

  discountValue?: string;

  discountUnit?: string;

  validTo?: Date;
}
