// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.discount */
export type DiscountId = string;

/** Represents the table public.discount */
export default interface Discount {
  id: DiscountId;

  discountName: string;

  campaignName: string;

  company: string;

  customerIds: string[];

  discountType: string;

  measureValueName: string | null;

  rangeFrom: string | null;

  rangeTo: string | null;

  discountValue: string;

  discountUnit: string;

  currency: string | null;

  validFrom: Date;

  validTo: Date | null;
}

/** Represents the initializer for the table public.discount */
export interface DiscountInitializer {
  /** Default value: uuidv7_sub_ms() */
  id?: DiscountId;

  discountName: string;

  campaignName: string;

  company: string;

  customerIds: string[];

  discountType: string;

  measureValueName?: string | null;

  rangeFrom?: string | null;

  rangeTo?: string | null;

  discountValue: string;

  discountUnit: string;

  currency?: string | null;

  validFrom: Date;

  validTo?: Date | null;
}

/** Represents the mutator for the table public.discount */
export interface DiscountMutator {
  id?: DiscountId;

  discountName?: string;

  campaignName?: string;

  company?: string;

  customerIds?: string[];

  discountType?: string;

  measureValueName?: string | null;

  rangeFrom?: string | null;

  rangeTo?: string | null;

  discountValue?: string;

  discountUnit?: string;

  currency?: string | null;

  validFrom?: Date;

  validTo?: Date | null;
}
