// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.invoice */
export type InvoiceCustomer_email = string;

/** Identifier type for public.invoice */
export type InvoiceCompany = string;

/** Identifier type for public.invoice */
export type InvoiceInvoice_date = Date;

/** Represents the table public.invoice */
export default interface Invoice {
  customerEmail: InvoiceCustomer_email;

  company: InvoiceCompany;

  invoiceDate: InvoiceInvoice_date;

  totalAmount: string;

  currency: string;

  status: string;
}

/** Represents the initializer for the table public.invoice */
export interface InvoiceInitializer {
  customerEmail: InvoiceCustomer_email;

  company: InvoiceCompany;

  /** Default value: now() */
  invoiceDate?: InvoiceInvoice_date;

  totalAmount: string;

  currency: string;

  /** Default value: 'pending'::character varying */
  status?: string;
}

/** Represents the mutator for the table public.invoice */
export interface InvoiceMutator {
  customerEmail?: InvoiceCustomer_email;

  company?: InvoiceCompany;

  invoiceDate?: InvoiceInvoice_date;

  totalAmount?: string;

  currency?: string;

  status?: string;
}
