// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.invoice_line_item */
export type Invoice_line_itemCustomer_email = string;

/** Identifier type for public.invoice_line_item */
export type Invoice_line_itemCompany = string;

/** Identifier type for public.invoice_line_item */
export type Invoice_line_itemInvoice_date = Date;

/** Identifier type for public.invoice_line_item */
export type Invoice_line_itemCampaign_name = string;

/** Identifier type for public.invoice_line_item */
export type Invoice_line_itemTariff_type = string;

/** Represents the table public.invoice_line_item */
export default interface InvoiceLineItem {
  customerEmail: Invoice_line_itemCustomer_email;

  company: Invoice_line_itemCompany;

  invoiceDate: Invoice_line_itemInvoice_date;

  campaignName: Invoice_line_itemCampaign_name;

  tariffType: Invoice_line_itemTariff_type;

  description: string;

  quantity: string;

  unitPrice: string;

  lineTotal: string;
}

/** Represents the initializer for the table public.invoice_line_item */
export interface InvoiceLineItemInitializer {
  customerEmail: Invoice_line_itemCustomer_email;

  company: Invoice_line_itemCompany;

  invoiceDate: Invoice_line_itemInvoice_date;

  campaignName: Invoice_line_itemCampaign_name;

  tariffType: Invoice_line_itemTariff_type;

  description: string;

  quantity: string;

  unitPrice: string;

  lineTotal: string;
}

/** Represents the mutator for the table public.invoice_line_item */
export interface InvoiceLineItemMutator {
  customerEmail?: Invoice_line_itemCustomer_email;

  company?: Invoice_line_itemCompany;

  invoiceDate?: Invoice_line_itemInvoice_date;

  campaignName?: Invoice_line_itemCampaign_name;

  tariffType?: Invoice_line_itemTariff_type;

  description?: string;

  quantity?: string;

  unitPrice?: string;

  lineTotal?: string;
}
