// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the table public.non_active_customer */
export default interface NonActiveCustomer {
  id: string;

  email: string;

  title: string | null;

  firstName: string;

  middleName: string | null;

  lastName: string;

  phoneNumber: string;

  company: string;

  entityId: string;

  archiveDate: Date;
}

/** Represents the initializer for the table public.non_active_customer */
export interface NonActiveCustomerInitializer {
  id: string;

  email: string;

  title?: string | null;

  firstName: string;

  middleName?: string | null;

  lastName: string;

  phoneNumber: string;

  company: string;

  entityId: string;

  /** Default value: now() */
  archiveDate?: Date;
}

/** Represents the mutator for the table public.non_active_customer */
export interface NonActiveCustomerMutator {
  id?: string;

  email?: string;

  title?: string | null;

  firstName?: string;

  middleName?: string | null;

  lastName?: string;

  phoneNumber?: string;

  company?: string;

  entityId?: string;

  archiveDate?: Date;
}
