// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.payment */
export type PaymentCustomer_email = string;

/** Identifier type for public.payment */
export type PaymentCompany = string;

/** Identifier type for public.payment */
export type PaymentInvoice_date = Date;

/** Identifier type for public.payment */
export type PaymentPayment_date = Date;

/** Identifier type for public.payment */
export type PaymentTransaction_id = string;

/** Represents the table public.payment */
export default interface Payment {
  customerEmail: PaymentCustomer_email;

  company: PaymentCompany;

  invoiceDate: PaymentInvoice_date;

  paymentDate: PaymentPayment_date;

  transactionId: PaymentTransaction_id;

  amount: string;

  currency: string;

  paymentMethod: string;
}

/** Represents the initializer for the table public.payment */
export interface PaymentInitializer {
  customerEmail: PaymentCustomer_email;

  company: PaymentCompany;

  invoiceDate: PaymentInvoice_date;

  /** Default value: now() */
  paymentDate?: PaymentPayment_date;

  transactionId: PaymentTransaction_id;

  amount: string;

  currency: string;

  paymentMethod: string;
}

/** Represents the mutator for the table public.payment */
export interface PaymentMutator {
  customerEmail?: PaymentCustomer_email;

  company?: PaymentCompany;

  invoiceDate?: PaymentInvoice_date;

  paymentDate?: PaymentPayment_date;

  transactionId?: PaymentTransaction_id;

  amount?: string;

  currency?: string;

  paymentMethod?: string;
}
