// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.reminder */
export type ReminderCampaign_name = string;

/** Identifier type for public.reminder */
export type ReminderReminder_date = Date;

/** Identifier type for public.reminder */
export type ReminderCompany = string;

/** Represents the table public.reminder */
export default interface Reminder {
    campaignName: ReminderCampaign_name;

    reminderDate: ReminderReminder_date;

    company: ReminderCompany;

    customerIds: string[];
}

/** Represents the initializer for the table public.reminder */
export interface ReminderInitializer {
    campaignName: ReminderCampaign_name;

    reminderDate: ReminderReminder_date;

    company: ReminderCompany;

    customerIds: string[];
}

/** Represents the mutator for the table public.reminder */
export interface ReminderMutator {
    campaignName?: ReminderCampaign_name;

    reminderDate?: ReminderReminder_date;

    company?: ReminderCompany;

    customerIds?: string[];
}
