// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.sessions */
export type SessionsId = number;

/** Represents the table public.sessions */
export default interface Sessions {
  id: SessionsId;

  userId: number;

  expires: Date;

  sessionToken: string;
}

/** Represents the initializer for the table public.sessions */
export interface SessionsInitializer {
  /** Default value: nextval('sessions_id_seq'::regclass) */
  id?: SessionsId;

  userId: number;

  expires: Date;

  sessionToken: string;
}

/** Represents the mutator for the table public.sessions */
export interface SessionsMutator {
  id?: SessionsId;

  userId?: number;

  expires?: Date;

  sessionToken?: string;
}
