// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.tariff */
export type TariffId = string;

/** Represents the table public.tariff */
export default interface Tariff {
  id: TariffId;

  campaignName: string;

  company: string;

  customerIds: string[];

  description: string;

  measureValueName: string | null;

  rate: string;

  currency: string;

  unit: string;

  rangeFrom: string | null;

  rangeTo: string | null;

  validFrom: Date;

  validTo: Date | null;

  isDeposit: boolean;
}

/** Represents the initializer for the table public.tariff */
export interface TariffInitializer {
  /** Default value: uuidv7_sub_ms() */
  id?: TariffId;

  campaignName: string;

  company: string;

  customerIds: string[];

  description: string;

  measureValueName?: string | null;

  rate: string;

  currency: string;

  unit: string;

  rangeFrom?: string | null;

  rangeTo?: string | null;

  validFrom: Date;

  validTo?: Date | null;
}

/** Represents the mutator for the table public.tariff */
export interface TariffMutator {
  id?: TariffId;

  campaignName?: string;

  company?: string;

  customerIds?: string[];

  description?: string;

  measureValueName?: string | null;

  rate?: string;

  currency?: string;

  unit?: string;

  rangeFrom?: string | null;

  rangeTo?: string | null;

  validFrom?: Date;

  validTo?: Date | null;
}
