// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.tariff */
export type TariffCampaign_name = string;

/** Identifier type for public.tariff */
export type TariffCompany = string;

/** Identifier type for public.tariff */
export type TariffTariff_type = string;

/** Identifier type for public.tariff */
export type TariffMeasure_value = string;

/** Identifier type for public.tariff */
export type TariffRange_from = string;

/** Identifier type for public.tariff */
export type TariffValid_from = Date;

/** Represents the table public.tariff */
export default interface Tariff {
  campaignName: TariffCampaign_name;

  company: TariffCompany;

  tariffType: TariffTariff_type;

  measureValue: TariffMeasure_value;

  rangeFrom: TariffRange_from;

  validFrom: TariffValid_from;

  rate: string;

  unit: string;

  rangeTo: string | null;

  validTo: Date;
}

/** Represents the initializer for the table public.tariff */
export interface TariffInitializer {
  campaignName: TariffCampaign_name;

  company: TariffCompany;

  tariffType: TariffTariff_type;

  measureValue: TariffMeasure_value;

  rangeFrom: TariffRange_from;

  validFrom: TariffValid_from;

  rate: string;

  unit: string;

  rangeTo?: string | null;

  validTo: Date;
}

/** Represents the mutator for the table public.tariff */
export interface TariffMutator {
  campaignName?: TariffCampaign_name;

  company?: TariffCompany;

  tariffType?: TariffTariff_type;

  measureValue?: TariffMeasure_value;

  rangeFrom?: TariffRange_from;

  validFrom?: TariffValid_from;

  rate?: string;

  unit?: string;

  rangeTo?: string | null;

  validTo?: Date;
}
