// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.users */
export type UsersId = number;

/** Represents the table public.users */
export default interface Users {
  id: UsersId;

  name: string | null;

  email: string | null;

  emailVerified: Date | null;

  image: string | null;

  role: string | null;

  company: string | null;
}

/** Represents the initializer for the table public.users */
export interface UsersInitializer {
  /** Default value: nextval('users_id_seq'::regclass) */
  id?: UsersId;

  name?: string | null;

  email?: string | null;

  emailVerified?: Date | null;

  image?: string | null;

  role?: string | null;

  company?: string | null;
}

/** Represents the mutator for the table public.users */
export interface UsersMutator {
  id?: UsersId;

  name?: string | null;

  email?: string | null;

  emailVerified?: Date | null;

  image?: string | null;

  role?: string | null;

  company?: string | null;
}
