export const languageSuggestions = [
    {value: 'en-US', label: 'English (US)'},
    {value: 'en-GB', label: 'English (UK)'},
    {value: 'nl-NL', label: 'Nederlands (NL)'},
    {value: 'de-DE', label: 'Deutsch (DE)'},
    {value: 'fr-FR', label: 'Français (FR)'},
    {value: 'es-ES', label: 'Español (ES)'},
    {value: 'it-IT', label: 'Italiano (IT)'},
    {value: 'pt-PT', label: 'Português (PT)'},
    {value: 'ru-RU', label: 'Русский (RU)'},
    {value: 'zh-CN', label: '中文 (CN)'},
    {value: 'ja-JP', label: '日本語 (JP)'},
    {value: 'ko-KR', label: '한국어 (KR)'},
    {value: 'ar-SA', label: 'العربية (SA)'},
];